const cards: any = [
  '/assets/imgs/img0.png',
  '/assets/imgs/img1.png',
  '/assets/imgs/img2.png',
  '/assets/imgs/img3.png',
  '/assets/imgs/img4.png',
  '/assets/imgs/img5.png',
  '/assets/imgs/img6.png',
  '/assets/imgs/img7.png',
  '/assets/imgs/img8.png',
  '/assets/imgs/img9.png',
  '/assets/imgs/img10.png',
  '/assets/imgs/img11.png'
];
export const cardsVector: any = [
  {
    id: 1,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage: '/assets/imgs/img0.png',
    clickable: true,
    matchingCardId: 2,
    matchCode: 'card1',
  },
  {
    id: 2,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img1.png',
    clickable: true,
    matchingCardId: 1,
    matchCode: 'card1',
  },
  {
    id: 3,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img2.png',
    clickable: true,
    matchingCardId: 4,
    matchCode: 'card2',
  },
  {
    id: 4,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img3.png',
    clickable: true,
    matchingCardId: 3,
    matchCode: 'card2',
  },
  {
    id: 5,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img4.png',
    clickable: true,
    matchingCardId: 6,
    matchCode: 'card3',
  },
  {
    id: 6,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img5.png',
    clickable: true,
    matchingCardId: 5,
    matchCode: 'card3',
  },
  {
    id: 7,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img6.png',
    clickable: true,
    matchingCardId: 8,
    matchCode: 'card4',
  },
  {
    id: 8,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img7.png',
    clickable: true,
    matchingCardId: '7',
    matchCode: 'card4',
  },
  {
    id: 9,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img8.png',
    clickable: true,
    matchingCardId: 10,
    matchCode: 'card5',
  },
  {
    id: 10,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img9.png',
    clickable: true,
    matchingCardId: 9,
    matchCode: 'card5',
  },
  {
    id: 11,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img10.png',
    clickable: true,
    matchingCardId: 12,
    matchCode: 'card6',
  },
  {
    id: 12,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage:  '/assets/imgs/img11.png',
    clickable: true,
    matchingCardId: 11,
    matchCode: 'card6',
  },
];

// Create card board
export const createBoard = () =>
  //Need 2 of each card
  [...cards].map((card, i) => ({
    id: `a`,
    flipped: false,
    backImage: '/assets/cardFront.png',
    frontImage: card,
    clickable: true,
    matchingCardId: 'a'
  }));
